### PR TITLE
Feature/ast split

### LINKED ISSUE #83: Divide the astexport.py module between pydetector and the driver
In the meeting planning we decided to split the functionality in the current `pydetector.astexport.py` module between the retrieval of the native AST data structure unmodified (but for the right Python version) in `pydetector` and the visitor + noop extractor + position updater in `python-driver`, reusing the data returned from `pydetector` to avoid doing a double parsing.

### PR DESCRIPTION
**Pull request by juanjux**
Second part of the split, the driver:

- Move here all the position, pre-annotations, comment extraction and any other modification to the native AST (in the dictionary format as exported by PyDetector, see PR bblfsh/python-pydetector/pull/23). In the process added a value property that was missing in the original implementation.

- Add synthetic tokens for all keywords that didn't have a native one.

- Remade integration tests (and checked them manually). 

- Removed some msgpack cruft from the `sendmsg.py` script (used for manually testing and debugging the full cycle).

The Travis CI will fail until pydetector is merged.

Fixes #83

### CODE REVIEW

**Comment by abeaumont** [comment]
I thought we were going to minimize the work on top of the native AST, yet there's still code to fix positions, etc. Am I missing something?

**Comment by juanjux** [comment]
@abeaumont the only position updates remaining are the ones that can be retrieved from the native tokenizer (end position + updated positions for nodes missing them) as we spoke on the meeting, plus changing the 0 based Python columns to 1 based since the SDK can convert col+pos to offset or the other way around but not one of the first to 1 based.

**Comment by juanjux** [comment]
@abeaumont I just saw one fix still to remove (the one for embedded code in f-strings), I'll remove that one too.

**Comment by abeaumont** [comment]
Ok, understood. Thanks for the info.

**Pull request merged**
