### PR TITLE
Third iteration; driver, rules, tonoder, tests and fixes

### PR DESCRIPTION
**Pull request by juanjux**
PR to the current state of my branch. Rebased and squashed a lot of commits, maybe too many (the messages are in the commit descriptions anyway) to keep the number of commits limited but they're still 15 since there was a lot of work on the driver since the last merge.

### CODE REVIEW

**Comment by juanjux** [comment]
I fixed the column numbers missing on some nodes in pydetector and updated the dependency so this Fixes #6

**Comment by smola** [comment]
@juanjux Please, rebase.

**Comment by juanjux** [comment]
@smola ok, will add the rules for the new UAST merged PRs and then rebase and ping you once its done

**Comment by juanjux** [comment]
@smola rebase done, I've fixed the conflicts with upstream and also added the new rules for the merged UAST nodes of maps and binaryexpressions. I also squashed a couple commits more. If you need even more squashing just tell me.

Travis is failing with some odd results, but integration tests work perfectly on my containers, maybe travis needs some SDK updating?

-.  .  .  .  .  Roles: Comment
+.  .  .  .  .  Roles: Role(132)

**Comment by juanjux** [comment]
Updated with the rules for the newly merged UAST nodes of TypeDefinitionBody and bases.

**Comment by smola** [comment]
@juanjux This is because `go generate ./uast/...` was not run on the sdk when adding roles. I've just fixed it.

**Pull request merged**
